//AUTH ACTION TYPES
export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const SET_USER = 'SET_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const REMOVE_USER = 'REMOVE_USER';
//errors
//AUTH ERROR TYPES
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const REMOVE_LOGIN_USER_ERROR = 'REMOVE_LOGIN_USER_ERROR';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const REMOVE_REGISTER_USER_ERROR = "REMOVE_REGISTER_USER_ERROR";
//TEMPLATE ACTION
export const INITIATE_TEMPLATE_CREATION = "INITIATE_TEMPLATE_CREATION";
//TEST
export const TEST = "TEST";