//AUTH ACTION TYPES
export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const SET_USER = 'SET_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const REMOVE_USER = 'REMOVE_USER';
//errors
//AUTH ERROR TYPES
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const REMOVE_LOGIN_USER_ERROR = 'REMOVE_LOGIN_USER_ERROR';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const REMOVE_REGISTER_USER_ERROR = "REMOVE_REGISTER_USER_ERROR";
//TEMPLATE ACTION
export const INITIATE_TEMPLATE_CREATION = "INITIATE_TEMPLATE_CREATION";
export const INITIATE_GET_TEMPLATES = "INITIATE_GET_TEMPLATES";
export const SET_TEMPLATES = "SET_TEMPLATES";
//OBJECT
export const INITIATE_OBJECT_CREATION = "INITIATE_OBJECT_CREATION";
export const SET_OBJECTS = "SET_OBJECTS";
//METRICS
export const INITITATE_EVENT_METRICS = "INITIATE_EVENT_METRICS";
export const SET_EVENT_METRICS = "SET_EVENT_METRICS";
//TEST
export const TEST = "TEST";